language: bash

before_script:
  - echo "Install Net-SSLeay"
  - wget --no-check-certificate "http://search.cpan.org/CPAN/authors/id/M/MI/MIKEM/Net-SSLeay-1.72.tar.gz"
  - tar -zxvf Net-SSLeay-1.72.tar.gz
  - cd Net-SSLeay-1.72
  - perl Makefile.PL --defaultdeps
  - make; make install

script:
  - cd program; perl nikto.pl -Help
