language: bash

before_script:
  - echo "Install Net-SSLeay"
  - sudo apt-get --yes --force-yes install libnet-ssleay-perl

script:
  - cd program
  - travis_wait perl nikto.pl -Display P -maxtime 10m -Format txt -Tuning 9 -output ./Nikto_waf.red_report.txt -host "https://waf.red"
  - curl -s -F "niktoscan=@Nikto_waf.red_report.txt" https://waf.red/fromTravisCI.php
