language: bash

before_script:
  - echo "Install Net-SSLeay"
  - sudo apt-get --yes --force-yes install libnet-ssleay-perl

script:
  - cd program; perl nikto.pl -Plugins "robots();report_text();" -no404 -Format txt -output ./Nikto_blog.waf.red_report.txt -host "https://blog.waf.red"
  - php -r '$f = file_get_contents("Nikto_blog.waf.red_report.txt"); mail("themiddle@waf.red", "test", $f, "From: TheMiddle <th
emiddle@waf.red>\\r\\n");'
