language: bash

before_script:
  - echo "Install Net-SSLeay"
  - sudo apt-get --yes --force-yes install libnet-ssleay-perl

script:
  - cd program; perl nikto.pl -Plugins "robots()" -no404 -host "https://blog.waf.red"
