language: bash

before_script:
  - echo "Install Net-SSLeay"
  - sudo apt-get --yes --force-yes install libnet-ssleay-perl

script:
  - cd program; perl nikto.pl -Plugins "robots();report_text();" -no404 -Format txt -output ./Nikto_blog.waf.red_report.txt -host "https://blog.waf.red"
  - cd ../; php -f sendreport.php "program/Nikto_blog.waf.red_report.txt"
